# Generated by Django 4.2.26 on 2025-12-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='fecha_primer_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='password_temporal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='usuario_creado',
            field=models.BooleanField(default=False),
        ),
    ]
